[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
source = "."
buildCommand = "npm install && npm run build"
startCommand = "npm start"

[[services]]
name = "backend"
source = "./server"
buildCommand = "npm install"
startCommand = "npm start"